### ISSUE TITLE
Header icons not showing

### ISSUE THREAD

**Issue by jdawsonadams** [jdawsonadams/ecommerce-pattern-library#2]
My logo icon isn't showing in my header, I've tried img src="/images/logo.svg" which also didn't work. It's supposed to be at the top left, I am not sure why it's not showing up :/

@thomasjbradley

**Comment by thomasjbradley** [comment]
For the logo, it looks like you need to use an `<img>` tag, like this:
https://github.com/jdawsonadams/ecommerce-pattern-library/blob/master/_patterns/header/header.html#L3

```html
 <i class="icon i-96 push-l-1-2 valign-middle"><img src="/images/logo.svg" alt=""></i>
```
