### ISSUE TITLE
Centering Image in Card

### ISSUE THREAD

**Issue by jdawsonadams** [jdawsonadams/ecommerce-pattern-library#5]
@mackenzierose

Hi Mackenzie! I'm trying to center the image of the gummy bear on my product-card but I can't seem to get it to work!

**Comment by MacKenzieRose** [comment]
It looks pretty centered to me; did you get this to work @jdawsonadams ?

**Comment by jdawsonadams** [comment]
> It looks pretty centered to me; did you get this to work @jdawsonadams ?
I realized the issue is that it's centered at full screen, but I guess I need to use grids to fix the alignment when it's at a smaller screen size. I would use grids right?

**Comment by MacKenzieRose** [comment]
Ah I see what's happening.

If you add a `class="img-flex"` directly on your `<img>` tag, you should have it work properly with your card (though it will size a little smaller, as the image is being constrained to the card's bounding box.

**Comment by jdawsonadams** [comment]
> Ah I see what's happening.
> 
> If you add a `class="img-flex"` directly on your `<img>` tag, you should have it work properly with your card (though it will size a little smaller, as the image is being constrained to the card's bounding box.

that worked! amazing thank youuuu

**Comment by MacKenzieRose** [comment]
If this issue has been resolved, feel free to close it :)

Cheers!
MacKenzie
